[package]
name = "x-toolkit-convert"
version = "0.1.0"
authors = ["xuyizhe <barrenbass@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
bs58 = "0.4.0"
